<a href="https://colab.research.google.com/github/1197050069/node-csv/blob/master/1197050069_Moch_Rizki_Alfian_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

UTS Individu

Nama : Moch Rizki Alfian
NIM : 1197050069
Kelas : B

Student grade
Dataset : student_grade
Algoritma : Linear Regresi Sederhana
Alasan : untuk memudahkan menentukan grade pada murid murid

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [ ]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.7848629811998585


In [ ]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 5.12792045  6.22136367  8.56237376  9.5433619   6.22136367]
 [ 5.12792045  5.12792045  8.56237376  9.5433619  15.05412397]
 [ 9.58563457  9.70183209  8.56237376 12.83627896 10.34665774]
 ...
 [10.34665774  9.70183209  5.12706951 12.83627896 12.83627896]
 [13.18894758 12.622897    5.12706951  9.5433619   9.5433619 ]
 [ 9.70183209  7.89733775  5.12706951  9.5433619   5.12792045]] [[[ 6  7  2  3  0]
  [ 7  7  1  0  3]
  [10  9  2  0  4]
  [11 10  2  0  0]
  [ 7  7  1  0  3]]

 [[ 6  7  2  3  0]
  [ 6  7  2  3  0]
  [10  9  2  0  4]
  [11 10  2  0  0]
  [15 15  2  0  0]]

 [[ 9 10  3  0  9]
  [11 10  2  1 12]
  [10  9  2  0  4]
  [12 13  2  0  4]
  [ 9 11  3  0  2]]

 ...

 [[ 9 11  3  0  2]
  [11 10  2  1 12]
  [ 6  6  2  1 13]
  [12 13  2  0  4]
  [12 13  2  0  4]]

 [[14 13  1  0  6]
  [14 12  2  0 20]
  [ 6  6  2  1 13]
  [11 10  2  0  0]
  [11 10  2  0  0]]

 [[11 10  2  1 12]
  [ 6  9  1  1  4]
  [ 6  6  2  1 13]
  [11 10  2  0  0]
  [ 6  7  2  3  0]]] [array([[ 0,  8,  9, 10,  8]